SET PAGESIZE 100
SET LINESIZE 200
COLUMN OWNER FORMAT A20
COLUMN TABLE_NAME FORMAT A30
SELECT owner, table_name FROM all_tables WHERE table_name IN ('USERS', 'TRANSACTIONS', 'BUDGETS') AND owner NOT IN ('SYS', 'SYSTEM', 'XDB', 'OUTLN', 'MDSYS', 'CTXSYS', 'APPQOSSYS', 'DVSYS', 'DVF', 'LBACSYS', 'OLAPSYS', 'ORDDATA', 'ORDSYS', 'SI_INFORMTN_SCHEMA', 'WMSYS');
EXIT;
