SET PAGESIZE 50;
SET LINESIZE 150;
COLUMN USERNAME FORMAT A15;
COLUMN EMAIL FORMAT A25;
PROMPT --- USERS TABLE ---
SELECT * FROM USERS;
COLUMN CATEGORY FORMAT A15;
COLUMN DESCRIPTION FORMAT A30;
PROMPT --- TRANSACTIONS TABLE ---
SELECT * FROM TRANSACTIONS;
EXIT;
